name: package-manager-ci

on:
  push:
    branches:
      - main

jobs:
  pnpm:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [10, 12]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with pnpm
        run: |
          npm i pnpm -g
          pnpm install

      - name: Run tests
        run: |
          pnpm run test

  yarn:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Maintenance and active LTS
        node-version: [10, 12]
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install with yarn
        run: |
          npm i yarn -g
          yarn install --ignore-engines

      - name: Run tests
        run: |
          yarn run test
